export default MEDIA = {
  // IMAGE_CNV: require('../assets/images/img_cnv.png'),
  // IMAGE_CV_01: require('../assets/images/img_cv_01.png'),
  // IMAGE_CV_02: require('../assets/images/img_cv_02.png'),
  // IMAGE_CV_03: require('../assets/images/img_cv_03.png'),
  // IMAGE_JOB_DETAIL: require('../assets/images/img_job_detail.png'),
  // IMAGE_LAYER: require('../assets/images/img_layer.png'),
  // IMAGE_LIST_JOB: require('../assets/images/img_list_job.png'),
  // IMAGE_LIST_JOB_2: require('../assets/images/img_list_job_2.png'),
  // IMAGE_LOGO: require('../assets/images/img_logo.png'),
  // IMAGE_NBM: require('../assets/images/img_nbm.png'),
  // IMAGE_LOGIN: require('../assets/images/img_login.png'),
  // IMAGE_FORGOT_PASS: require('../assets/images/img_forgot.png'),
  // IMAGE_CV: require('../assets/images/img_cv.png'),
  // IMAGE_LOGIN_BACKGROUND_1: require('../assets/images/login_background1.jpg'),
  // IMAGE_LOGIN_BACKGROUND_2: require('../assets/images/login_background2.jpg'),
  // IMAGE_LOGIN_BACKGROUND_3: require('../assets/images/login_background3.jpg'),
  // IMAGE_LOGIN_BACKGROUND_4: require('../assets/images/login_background4.jpg'),

  // Switch codepush

  IMAGE_CNV: require('../../assets/images/img_cnv.png'),
  IMAGE_CV_01: require('../../assets/images/img_cv_01.png'),
  IMAGE_CV_02: require('../../assets/images/img_cv_02.png'),
  IMAGE_CV_03: require('../../assets/images/img_cv_03.png'),
  IMAGE_JOB_DETAIL: require('../../assets/images/img_job_detail.png'),
  IMAGE_LAYER: require('../../assets/images/img_layer.png'),
  IMAGE_LIST_JOB: require('../../assets/images/img_list_job.png'),
  IMAGE_LIST_JOB_2: require('../../assets/images/img_list_job_2.png'),
  IMAGE_LOGO: require('../../assets/images/img_logo.png'),
  IMAGE_NBM: require('../../assets/images/img_nbm.png'),
  IMAGE_LOGIN: require('../../assets/images/img_login.png'),
  IMAGE_FORGOT_PASS: require('../../assets/images/img_forgot.png'),
  IMAGE_CV: require('../../assets/images/img_cv.png'),
  IMAGE_LOGIN_BACKGROUND_1: require('../../assets/images/login_background1.jpg'),
  IMAGE_LOGIN_BACKGROUND_2: require('../../assets/images/login_background2.jpg'),
  IMAGE_LOGIN_BACKGROUND_3: require('../../assets/images/login_background3.jpg'),
  IMAGE_LOGIN_BACKGROUND_4: require('../../assets/images/login_background4.jpg'),
};
